### ISSUE TITLE
Do the Needful - Unable to connect to server after installing ModPack

### ISSUE THREAD

**Issue by hobart151** [aboutell/TheThickeningRoom#2]
Make this your priority 1 item.  Customer Sev1 and complaining.  You've seen the pictures, here are the log files.
hobart151 user.
[latest.log](https://github.com/aboutell/TheThickeningRoom/files/4536606/latest.log)
[debug.log](https://github.com/aboutell/TheThickeningRoom/files/4536607/debug.log)

**Comment by aboutell** [comment]
I am still researching this issue, but would it be possible for you to send me a screenshot for your .minecraft\mods directory so that I can compare it to mine to determine if there is a missing mod?

The errors in the latest.log indicate that the the mod files don't exist.
===================================================
[26Apr2020 18:24:28.546] [Netty Client IO #0/ERROR] [net.minecraftforge.fml.network.NetworkRegistry/NETREGISTRY]: **_The server is likely to require channel_ [[mekanism:mekanism, cfm:network, storagedrawers:main_channel, vehicle:network]] _to be present, yet we don't have it_**

**Comment by hobart151** [comment]
![Github2_pic1](https://user-images.githubusercontent.com/63978256/80980544-bec0d080-8df6-11ea-979d-25cbad1fc207.jpg)
Here is the screenshot.  The mods directory just has two sub-directories in it, and the "Fabric" one has the new files in it.

**Comment by aboutell** [comment]
Ok,  looks like the installer messed up during installation.  Do the following:

1) Select all .jar files **EXCEPT** VoxelMap-Mod-Fabric-1.14.4.jar
2) Cut files from this directory
3) Go back 1 directory
4) Paste selected files in this directory. (Should be .minecraft\mods\)
5) Load your game > Load the multiplayer server (remember to ignore the red X) > Continue working on my face...

Let me know if this solves your issue!!

**Comment by aboutell** [comment]
Have you had a chance to test this resolution?  If so, please do the needful and report back to me!!

**Comment by hobart151** [comment]
It works, thank Sandy!  At first I got the attached "Crash" screen.
![MC_Crash](https://user-images.githubusercontent.com/63978256/82240156-f015c200-9907-11ea-8438-8c405fb96964.jpg)

But trying again, I was able to log in.  Like usual, I won't thank you for helping work this and making it priority one (like the towel-heads at work - they just expect top notch dedicated service).
Love you.

**Comment by hobart151** [comment]
Done. Ticket updated and closed. Thank Sandy

Love
Dad

________________________________
